// <auto-generated />
namespace EFCodeFirstDemoProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MyNew1EntityDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MyNew1EntityDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202312131103066_MyNew1EntityDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
